const schnorrer = [
       // 0.0-0.9
       [
        "Boah, Bruder… das sieht echt aus wie das letzte Kraut aus’m Komposthaufen. Knollen wie Vogelfutter, trocken wie altes Heu, und die Farbe? Eher grau-braun als grün – ich würd fast schwören, das hat schon zweimal Schimmel gesehen. Geruch? Wenn man die Nase reinsteckt, kriegt man mehr Stallgeruch als Grasduft. Geschmacklich vermutlich so, als ob man einen alten Teppich raucht. Wirkung? Vielleicht ’n ganz leichter Druck im Kopf, aber wahrscheinlich mehr Kopfschmerzen als Rausch. Trocknungsgrad? Komplett über, staubt schon beim Anfassen. Aber ey, bevor du’s wegwirfst – gib mir doch lieber einen kleinen Bud ab, ich probier das gern auf Risiko!",
        "Boah, sieht aus wie das Zeug, was man früher auf’m Schulhof in Alufolie gekriegt hat. Komplett trocken, null Harz, bröselt beim Angucken. Geruch? Eher nach Omas Mottenkugeln als nach Gras. Geschmacklich kratzt das sicher ordentlich im Hals, so ’n richtiger ‚Hustenanzünder‘. Wirkung? Wenn man Glück hat, leichter Schwindel. Trocknung? Übertrieben, das knackt wie trockenes Herbstlaub. Aber hey, bevor du’s wegschmeißt, geb mir ruhig ’ne Ecke – vielleicht kann man ja ’n Spliff draus drehen.",
        "Alter… das ist Hecke der Kategorie ‚Notfallreserve im Schuhkarton‘. Verfärbt, voll mit Stängeln, nix, was man Freunden zeigen könnte. Geruch: wie altes Heu vom Bauernhof. Geschmack: bestimmt bitter wie alter Kaffee. Wirkung? Bestenfalls ein leichtes Blubbern im Kopf, aber nix, was ballert. Trocknungsgrad? Staubig! Trotzdem – Bruder, wenn du das eh nicht rauchst, lass mich mal probieren, vielleicht geht da ja doch noch was!",
        "Ey, das schreit nach Restposten. Buds klein, fluffig, kaum Harz, fast mehr Stängel als alles andere. Riecht wie ’ne Mischung aus feuchtem Karton und nassem Gras. Geschmack wahrscheinlich noch schlimmer – so, als würdest du Tee aus Brennnesseln rauchen. Wirkung? Wahrscheinlich Nullnummer, vielleicht bisschen müde, aber bestimmt keine Euphorie. Trocknung überzogen, staubt beim Drehen. Aber Digga, wenn du eh keinen Bock drauf hast, ich nehm das mit Kusshand. Für mich zählt: Hauptsache brennt!",
        "Uff, also optisch ist das wirklich Endstufe Kellergras. Grau-grün, fast farblos, als ob das schon paar Sommer im Schuhkarton gelegen hat. Trichome? Fehlanzeige. Geruch? Riecht eher wie altes Brot, bisschen muffig, so ’n Keller-Vibe. Geschmacklich bestimmt bitter und kratzt im Hals, da brauchst du direkt Wasser daneben. Wirkung? Vielleicht bisschen Schwere auf den Augenlidern, aber sonst nix. Bruder, ich weiß das ist nix zum Angeben, aber guck mal, ich bin da nicht so wählerisch... wenn du eh nichts damit anfangen kannst, lass mir das lieber, ich bastel mir da trotzdem noch ’nen Joint draus.",
        "Digga, ich sag’s dir ehrlich: das sieht nicht nach Weed aus, sondern nach dem, was beim Kehren unterm Sofa übrig bleibt. Komplett zerbröselt, null Struktur, nix, was man Bud nennen könnte. Farbe? Mehr grau-braun als grün, richtig traurig. Geruch? Wenn man die Nase reinsteckt, kommt da nix außer muffiger Keller, so als ob’s drei Monate im Schuhkarton neben alten Turnschuhen lag. Geschmack stell ich mir wie verbranntes Papier vor, bestimmt kratzt das so, dass man nach zwei Zügen heiser ist. Wirkung? Bruder, höchstens Placebo – wenn du Glück hast, wirst du müde, wenn du Pech hast, nur Kopfschmerzen. Trocknungsgrad? Übertrieben, das zerfällt zu Staub, bevor du den Grinder überhaupt siehst. Aber ey – ich bin da nicht zu stolz: gib mir doch was davon ab, ich würd’s trotzdem testen. Hauptsache irgendwas brennt, verstehst du?",
        "Ey, also das hier ist wirklich Endgegner-Hecke. Sieht so aus, als ob jemand im Herbst Laub gesammelt und in die Tüte gestopft hat. Nur Stängel und Krümel, null Harz, null Glanz. Geruch? Ich schwör, das riecht eher nach feuchtem Karton oder altem Staubsaugerbeutel als nach Gras. Geschmack? Bruder, ich kann mir vorstellen, wie’s im Hals brennt – bitter, kratzig, einfach widerlich. Wirkung? Forget it – du wirst eher hungrig, weil du nach ’nem Snack suchst, um den Nachgeschmack loszuwerden. Trocknung? Staubtrocken, aber gleichzeitig so altfeucht, dass es schon muffig riecht. Ganz ehrlich, keiner will das rauchen – außer mir vielleicht. Wenn du eh nix damit anfangen kannst, pack mir doch was ein, ich nehm das als ‚Testobjekt",
        "Bruder, das ist nicht mal mehr zweite Liga – das ist Kreisklasse Abstieg. Optisch wie Vogelfutter, nur kleine Samen und Reste, fast nix Grünes. Riecht wie altes Gras vom Straßenrand, da ist kein Hauch von Terpen drin. Geschmacklich? Ich schwör, als würdest du verbrannte Kräuter aus’m Gewürzregal ziehen – Muskat und Oregano, nur schlimmer. Wirkung? Vielleicht ein ganz kurzer Schwindel, aber das könnte auch vom Husten kommen. Trocknungsgrad? Staubig, knackt schon beim Anfassen, fällt in Krümel auseinander. Digga, niemand mit Verstand würde das noch rauchen – aber rate mal? Ich würd trotzdem nen Kopf probieren. Einfach weil: besser schlechte Hecke als gar keine Hecke, weißt du?",
        "Das ist kein Gras, das ist ein botanischer Burnout. Die Farbe? Irgendwo zwischen Altgrün und Staubsaugerbeutel. Die Buds? Fehlanzeige. Das ist mehr Stängel als Substanz – wie ein Salat, den man vergessen hat zu gießen. Ich hab dran gerochen und mein Gehirn hat kurz gestreikt. Es roch wie feuchte Pappe mit einem Hauch von Kellerkind. Aber ich bin ja kein Feigling. Ich hab mir trotzdem ’nen Köpfchen gegönnt – aus Prinzip und Mangel an Alternativen. Der Geschmack? Bruder, ich hab schon an Kloschüsseln geleckt, die angenehmer waren. Mein Hals hat sich angefühlt wie Schleifpapier. Und die Wirkung? Ich hab gewartet… und dann hab ich angefangen, meine Steuererklärung zu sortieren. Das Gras hat mich nicht high gemacht – es hat mich produktiv gemacht. Trocknungsgrad? Bröselig wie altes Croissant, aber trotzdem irgendwie klamm. Ich glaub, das Ding lebt noch. Aber ey – wenn du das wegwerfen willst, gib’s lieber mir – ich bin wie ein Bio-Mülleimer mit Feuerzeug.",
        "Sie sah aus wie der Inhalt eines missglückten Kräutertees. Dunkelbraun, kompakt, und mit der Aura von „Ich war mal lebendig“. Ich hab versucht, einen Bud zu finden – aber das war wie Ostereier suchen im November. Der Geruch? Eine Mischung aus nassem Hund, Erde und dem Gefühl, dass man was Besseres verdient hat. Ich hab dran geschnuppert und mein Nasenhaar hat sich freiwillig verabschiedet. Geschmacklich war’s ein Desaster. Ich hab’s geraucht und mein Gaumen hat sich in eine Wüste verwandelt. Bitter, kratzig, und irgendwie metallisch – als hätte ich versehentlich ’ne Büroklammer mitgeraucht. Die Wirkung? Bruder, ich bin nicht high geworden, ich bin philosophisch geworden. Ich hab angefangen, über meine Ex nachzudenken. Das Gras hat mich nicht berauscht – es hat mich therapiert. Trocknungsgrad? Feucht wie ein Schwamm, aber trotzdem bröselig. Ich glaub, das Ding hat seine eigene Klimazone. Aber ey, ich nehm auch den Bodensatz – Hauptsache irgendwas kratzt im Hals und beruhigt mein Gewissen."
      ],
      // 1.0-1.9
      [
        "Ey Bruder, das sieht schon minimal besser aus als der letzte Staubsaugerbeutel, aber ehrlich – weit weg von Rauchware. Die Buds sind so fluffig, dass man durchgucken kann, keine Dichte, null Harzschicht. Farbe so blassgrün mit braunen Flecken, nicht gerade sexy. Geruch? Ein bisschen Grasnote ist da, aber sehr schwach, mehr nach altem Rasen als nach Cannabis. Geschmack stell ich mir staubig-kratzig vor, so dass du nach drei Zügen husten musst. Wirkung? Vielleicht ein kleines Augenlied-Hängen, aber nix, was man Rausch nennen kann. Trocknung? Unsauber – außen staubtrocken, innen bisschen klamm. Aber Bruder, ich schwör dir, ich würd mir trotzdem nen Spliff damit drehen – besser als nix, verstehst du?",
        "Also ganz ehrlich, Digga, das ist Weed für harte Zeiten. Buds sind halbwegs erkennbar, aber super klein, voller Stängel und schon fast mehr Samen als alles andere. Farbe mattgrün, bisschen bräunlich, sieht traurig aus. Geruch? So’n schwaches Gras-Aroma, als hätte man’s neben Basilikum im Küchenschrank gelagert. Geschmack? Dünn und kratzig, wahrscheinlich bitter – der Joint macht keinen Spaß. Wirkung? Minimal beruhigend, aber das kannst du auch von ’ner warmen Milch haben. Trocknungsgrad? Eher übertrieben, zerbröselt sofort. Bruder, das ist nix zum Angeben, aber ich würd’s safe nehmen – so Reste sind genau mein Ding.",
        "Digga, guck dir das mal an – man erkennt, dass das mal Gras war, aber es sieht echt aus wie zweite Wahl vom Straßenrand. Buds? Kaum vorhanden, mehr Bröselhaufen als alles andere. Geruch? Ja, bisschen Grasnote kommt durch, aber sehr schwach, nicht das, was man erwartet. Geschmack? Dünn, flach, kratzt, aber nicht ganz so schlimm wie ganz unten bei 0 Punkten. Wirkung? Ein leichtes Kribbeln, vielleicht wirst du ein bisschen gechillt, aber High ist anders. Trocknung? Unsauber – außen bröselig, innen immer noch leicht feucht. Fazit: Für die Galerie unbrauchbar, für mich genau richtig – Bruder, pack mir ein paar Brösel ab, ich bastel mir da noch was draus.",
        "Bruder… ich hab dieses Gras gesehen und mein erster Gedanke war: „Das sieht aus wie das, was man findet, wenn man unter’m Sofa nach dem Feuerzeug sucht.“ Die Farbe? Irgendwas zwischen Olivgrün und Altbraun – wie ein Avocado-Rest, der sich nicht entscheiden kann, ob er noch lebt. Die Buds waren da, aber so klein, dass ich fast ’ne Lupe gebraucht hab. Geruch? Joa… es riecht wie ein Mix aus altem Tee, feuchtem Karton und dem Hauch von „Ich war mal Gras“. Ich hab’s trotzdem geraucht – weil ich Prinzipien hab. Der Geschmack war wie ein Waldspaziergang im November, aber ohne Bäume. Kratzig, bitter, und mein Hals hat direkt nach Gleitcreme geschrien. Die Wirkung? Ich hab kurz gedacht, ich spür was – aber das war nur mein Kreislauf, der sich verabschiedet hat. Trocknungsgrad? Trocken, aber nicht auf die gute Weise. Eher wie ein altes Brötchen vom Vortag. Aber Bruder… gib mir trotzdem was davon. Ich misch’s mit Tabak und tu so, als wär’s ein medizinisches Experiment.",
        "Also das hier… das war wie ein Date, bei dem du denkst: „Könnte was werden“ – und dann redet sie nur über ihre Katze. Optisch war’s okay-ish. Die Buds waren da, aber irgendwie unförmig – wie kleine Brocken Hoffnung. Die Farbe war grün, aber so matt, dass selbst mein Zimmerpflanze beleidigt geguckt hat. Geruch? Ein Hauch von Gras, gemischt mit dem Duft von altem Schrank. Nicht ekelhaft, aber auch nicht einladend. Ich hab mir ’nen Köpfchen gebaut und beim ersten Zug gedacht: „Geht klar.“ Beim zweiten Zug hat mein Hals dann gestreikt. Geschmacklich war’s wie ein Kräutertee, den man zu lange ziehen lässt – bitter, trocken, und irgendwie nach Papier. Die Wirkung? Ich war kurz benebelt, aber eher wie nach drei Stunden Netflix – nicht wie nach gutem Gras. Trocknungsgrad? Ganz okay, aber irgendwie zu schnell getrocknet. Wie wenn man Nudeln ohne Wasser kocht. Aber ey, Bruder… wenn du noch was hast, ich nehm’s. Vielleicht wird’s besser, wenn ich dabei die Augen zumache.",
        "Ich hab dieses Zeug bekommen mit den Worten: „Ist nicht das Beste, aber macht was.“ Bruder… das war wie zu sagen: „Dieser Döner ist nicht schlecht, er ist einfach nur kalt und ohne Fleisch.“ Aussehen? Klein, bröselig, und mit mehr Stängel als Inhalt. Die Farbe war wie ein altes Sofakissen – grün, aber traurig. Geruch? Ich hab dran geschnuppert und mein Gehirn hat gesagt: „Bruder, das ist kein Gras, das ist ein botanischer Witz.“ Geschmack? Ich hab’s geraucht und mein Mund hat sich in eine Baustelle verwandelt. Trocken, bitter, und mit einem Hauch von „Warum tust du dir das an?“ Wirkung? Ich hab kurz gezuckt – aber das war nur mein Magen. Kein High, nur Reue. Trocknungsgrad? So trocken, dass ich beim Zerbröseln Staub eingeatmet hab. Ich hab gehustet, bevor ich überhaupt gezogen hab. Aber Bruder… gib mir trotzdem was. Ich misch’s mit Optimismus und tu so, als wär’s ein spiritueller Prozess."
      ],
      // 2.0-2.9
      [
        "Okay, Digga, das sieht schon nicht mehr ganz nach Kompost aus, aber geil ist es auch nicht. Die Buds sind leicht grün, bisschen kompakter als bei den ganz miesen Sachen, aber trotzdem fluffig und voller Stängel. Harz? Kaum vorhanden, man muss echt suchen. Geruch? Da kommt wenigstens so’n leichter Grasduft durch, aber sehr dünn, erinnert eher an frisch gemähtes Heu. Geschmack? Bisschen besser, kratzt trotzdem, null Terpenprofil, einfach flach. Wirkung? Ein leichtes, kurzes High, so dass du denkst: ‚Ok, da ist was‘ – und fünf Minuten später ist’s schon weg. Trocknungsgrad? Immer noch nicht rund, teils zu trocken, teils noch feucht. Bruder, für die meisten unrauchbar – aber ich würd mir damit easy nen Kopf bauen, hauptsache da geht was rein.",
        "Ey Bruder, bei dem Zeug merkt man: da war mal Gras im Spiel, aber es hat’s nicht weit gebracht. Optisch immerhin grün, ein paar kleine Kristalle sieht man vielleicht, wenn man das Handylicht draufhält. Buds sind locker und klein, nix Kompaktes. Geruch? Joa, riecht schwach nach Weed, aber eher so nach Standard-Outdoor ohne Druck. Geschmack? Zieht durch, aber nicht angenehm, kratzt, nix Besonderes. Wirkung? Ganz leichter Entspannungsfaktor, bisschen müde vielleicht, aber nix, was du feiern würdest. Trocknung ist auch ungleichmäßig – ein Teil zu bröselig, der andere Teil klebt noch. Aber ey, ich bin ehrlich – das reicht mir schon, ich würd das safe mitnehmen. Hauptsache, der Joint glüht.",
        "Digga, guck mal, das ist Weed in der Kategorie ‚gerade noch erkennbar‘. Buds so mittelmäßig, bisschen grün, bisschen gelblich, nix was man fotografiert. Trichome? Ja, vielleicht zwei, wenn man die Augen zukneift. Geruch? Leicht grasig, bisschen erdig, aber sehr schwach. Geschmack? Bruder, das ballert keinen – das ist wie ne fade Suppe: kann man essen, macht aber keinen Spaß. Wirkung? Leichtes Body-Chill, aber so schwach, dass du danach denkst: ‚Hab ich überhaupt was geraucht?‘ Trocknungsgrad? Bröselig, aber nicht komplett Staub. Also ja, für die Galerie ein Flop – aber für mich? Bruder, gib mir ruhig nen Batzen davon, ich zieh mir das easy rein, kein Problem.",
        "Bruder… ich hab schon viel geraucht. Ich hab mal ’ne Tüte gebaut aus dem Inhalt eines Aschenbechers, weil ich dachte, da wär noch was drin. Aber das hier? Die Buds sehen aus wie die Reste vom Resteessen – klein, zerfleddert, und mit mehr Stängel als Substanz. Die Farbe? Irgendwo zwischen Altgrün und „Ich wurde in einer Socke transportiert“. Geruch? Ein Hauch von Gras, aber auch ein Hauch von feuchtem Keller und vergessener Turnhalle. Ich hab mir trotzdem ein Köpfchen gebaut – für den sozialen Frieden. Der Geschmack? Wie ein Kräutertee, den man mit Zigarettenasche verfeinert hat. Mein Hals hat sich direkt gemeldet: „Bruder, das war unnötig.“ Die Wirkung? Ich war kurz benebelt, aber eher wie nach einem langen Einkauf bei Kik. Kein echtes High, nur so ein „Ich könnte jetzt schlafen“-Vibe. Trocknungsgrad? Bröselig, aber irgendwie klamm. Wie ein Handtuch, das zu früh von der Leine genommen wurde. Aber Bruder… gib mir trotzdem was. Ich misch’s mit Pfefferminztee und tu so, als wär’s Wellness auf Hartz-IV-Niveau.",
        "Bruder… diese Hecke sieht aus, als hätte sie ein schweres Leben hinter sich. So richtig mit Jugendamt, Therapie und drei Umzügen. Die Buds? Klein, zerfleddert, und mit mehr Stängel als Inhalt. Die Farbe ist so matt, dass selbst meine Zimmerpflanze beleidigt geguckt hat. Geruch? Ein Mix aus altem Kräutertee und dem muffigen Charme eines WG-Kellers. Ich hab trotzdem gezogen – aus Respekt vor der Pflanze. Geschmacklich war’s wie ein Waldspaziergang mit nassen Socken. Die Wirkung? Ich war kurz benebelt, aber eher wie nach einem langen Gespräch mit meiner Bankberaterin. Trocknungsgrad? Bröselig, aber irgendwie feucht. Wie ein Toast, den man zu früh aus dem Toaster holt. Aber Bruder… gib mir trotzdem was. Ich rauch das aus Solidarität – für alle Hecken, die nie eine Chance hatten.",
        "Bro… das hier war wie ein Joint, der von einem Praktikanten gebaut wurde – mit viel Mühe, aber null Ahnung. Die Buds waren da, aber irgendwie unförmig – wie kleine Brocken Hoffnung. Die Farbe war grün, aber so matt, dass selbst mein Zimmerpflanze beleidigt geguckt hat. Geruch? Ein bisschen süßlich, ein bisschen erdig aber auch ein Hauch von „Ich wurde neben Waschmittel gelagert“. Ich hab mir ’nen Joint gebaut und beim ersten Zug gedacht: „Geht klar.“ Beim zweiten Zug hat mein Hals dann gesagt: „Bruder, das war’s.“ Geschmacklich war’s wie ein Mix aus Salbei, Papier und Enttäuschung. Die Wirkung? Ich war kurz motiviert, den Müll rauszubringen – aber dann hab ich’s gelassen. Kein echtes High, nur so ein „Ich tu so, als wär ich produktiv“-Vibe. Trocknungsgrad? Trocken, aber nicht bröselig. Eher wie ein altes Brötchen, das man noch essen könnte – aber nicht sollte. Aber Bruder… gib mir trotzdem was. Ich rauch das aus Prinzip – und weil ich grad eh nix zu verlieren hab."
      ],
      // 3.0-3.9
      [
        "Ich kam in die Runde, hatte wie immer nix dabei – kein Tabak, keine Papers, nicht mal ein Feuerzeug. Aber ich hatte Timing. Die Tüte war gerade im Bau, und ich hab direkt gesagt: „Ey, sieht stabil aus, was ist das für’n Strain?“ – als wär ich Teil des Prozesses. Die Buds waren okay, bisschen trocken, aber mit Struktur. Farbe? Solides Grün, mit dem Selbstbewusstsein eines Bio-Siegels vom Discounter. Geruch war dezent, Geschmack ging klar – nicht spektakulär, aber stabil. Ich hab gezogen und gesagt: „Geht klar für Dienstag.“ Wirkung? Ich war nicht high, aber angenehm verwirrt – wie nach einem Gespräch mit einem Philosophie-Studenten. Und obwohl ich nichts beigesteuert hab, hab ich die Tüte verteidigt, als wär’s meine. „Bruder, das ist besser als das, was ich letztens hatte“ – obwohl ich seit Tagen nix hatte. ",
        "Die Tüte war perfekt gebaut – nicht von mir, natürlich. Ich kam zu spät, hatte nix dabei, und trotzdem saß ich mit im Kreis. Ich hab gefragt: „Ey, darf ich den letzten Zug?“ – und hab ihn bekommen, mit einem Lächeln, das sagte: „Du bist eh immer da.“ Die Buds waren fluffig, die Farbe war satt, und der Geruch hat mich kurz an bessere Zeiten erinnert. Geschmack? Mild, angenehm, mit einem Hauch von Zitrus und Selbstachtung. Wirkung? Ich war kurz glücklich, dann zufrieden. Kein Drama, kein Absturz – einfach ein gutes Gefühl. Ich bin wie ein Bonuslevel – du weißt nicht, warum ich da bin, aber irgendwie passt’s. Und wenn du mich fragst, sag ich: „Bruder, ich bring beim nächsten Mal was mit.“ Sag ich jedes Mal.",
        "Ich war eigentlich nur auf Durchreise, wollte kurz Hallo sagen. Wirklich Zufall Digga. Die Tüte war schon halb durch, aber ich hab gefragt: „Ey, ist da noch was drin?“ – mit dem Tonfall von jemandem, der so tut, als wär das selbstverständlich. Die Buds waren mittelmäßig, aber der Move von mir war Premium. Geschmack? Wie Petersilie mit einem Hauch von Baustelle. Und die Wirkung? Ich war kurz still – das passiert selten. Ich hab sogar kurz vergessen, dass ich kein Tabak, kein Paper, kein Feuer habe – also noch ’nen ordentlichen Zug genommen. Ich hab gefragt, ob jemand Feuer hat und bin dann schnell mit dem Joint abgehauen. Ich bin wie ein Taxi, das du rufst – ich komm ohne Geld, aber mit Absicht.",
        "Ey Bruder, das hier ist schon nicht mehr ganz Katastrophe. Die Buds sehen wenigstens nach Gras aus – bisschen grün, bisschen fluffig, aber immerhin erkennbar. Harzschicht? Joa, so ein Hauch, aber du musst schon genau hingucken. Geruch? Grasig, leicht erdig, aber sehr flach, da fehlt der Druck. Geschmack? Geht runter, kratzt aber trotzdem im Hals, keine besonderen Noten. Wirkung? Ganz leicht beruhigend, bisschen kicherig vielleicht, aber viel zu kurz. Trocknung? Uneinheitlich – außen staubig, innen klamm. Bruder, für die Galerie vielleicht ein Reinfall, aber für mich? Perfekt, ich würd sofort nen Spliff damit bauen.",
        "Digga, man merkt, hier wurde schon versucht, was Ordentliches hinzukriegen, aber es reicht nicht. Buds sehen klein und locker aus, keine richtig dichten Nuggets. Farbe so blassgrün, mit braunen Stellen. Geruch? Immerhin nach Gras, aber sehr schwach – als ob jemand die gute Hecke mit Wasser verdünnt hat. Geschmack? Flach, kratzt, aber nicht ganz so schlimm wie die 2-Punkte-Kategorie. Wirkung? Joa, leichter Druck im Kopf, bisschen Schwere im Körper, aber hält kaum. Trocknung? Bröselt zwar, aber nicht ganz zu Staub. Ganz ehrlich, Bruder – ich würd das easy nehmen. Für mich reicht das dicke, auch wenn andere lachen würden.",
        "Ey, das hier ist Hecke der Sorte ‚man erkennt’s schon, aber keiner will’s haben‘. Buds sehen so lala aus, grünlich, aber unförmig, fluffig, kaum Harz. Geruch? Joa, bisschen nach Gras, aber sehr schwach, so dass du die Nase tief reinstecken musst. Geschmack? Dünn, kratzt, nix Terpenmäßiges. Wirkung? Ein leichtes, kurzes Kopf-High, aber das verfliegt schnell, du bist schneller wieder klar als dir lieb ist. Trocknung? Unregelmäßig, teils bröselig, teils feucht. Aber Bruder, du kennst mich – ich würd das trotzdem nehmen. Für mich ist das genau die Art Zeug, die man einfach durchzieht, ohne groß nachzudenken."
      ],
      // 4.0-4.9
      [
        "Bruder, das hier… das ist genau die Art Hecke, die ich feier. Guck mal: die Buds sind zwar nicht fett, aber immerhin grün und bisschen kompakt, man erkennt direkt – ja, das ist Gras. Harz? Joa, bissl was glitzert, reicht mir. Geruch? Angenehm grasig, so dass man beim Aufmachen denkt: ‚Ah, läuft.‘ Geschmack? Nicht der Burner, bisschen kratzig, aber Digga – solange’s ballert, bin ich dabei. Wirkung? Ganz solide, man spürt’s im Kopf, bisschen Body-Chill – perfekt für mich. Trocknung auch okay, nicht Staub, nicht zu nass. Ey Bruder, ganz ehrlich: so was brauch ich. Hast du da was für mich? Ich schwör, ich bring nächstes Mal auch was mit… aber heute lass mich erstmal von deinem drehen, ja?",
        "Digga, also das ist so Gras, das man easy wegschnorren kann. Buds klein, bissl fluffig, aber immerhin harzig genug, dass man was sieht. Geruch? Schön grasig, bisschen erdig, gar nicht so schlecht. Geschmack? Joa, kratzt ein bisschen, aber ich nehm auch Krümel vom Teppich, Bruder – ich bin da nicht wählerisch. Wirkung? Kommt leicht durch, macht bisschen locker im Kopf, reicht mir vollkommen. Trocknungsgrad passt – grindet sich gut, kein Staub, keine Pampe. Und ey, ganz ehrlich: wenn du das eh rauchst, dreh mal bitte ’nen Dicken, ich geb dir auch Feuer… also, wenn mein Feuerzeug nicht leer wär. Lass mich doch erstmal bei dir ziehen, dann sehen wir weiter.",
        "Bruder, das sieht schon ziemlich stabil aus im Vergleich zu dem, was ich sonst schnorre. Buds mittelgroß, leicht sticky, man merkt, da steckt schon bisschen Liebe drin. Geruch? Angenehm, leicht süßlich-erdig, macht direkt Bock. Geschmack? Schön rauchbar, kratzt nur minimal – ich würd das sofort inhalieren, selbst wenn’s vom Boden aufgehoben wär. Wirkung? Kommt chillig, entspannt, aber haut nicht um. Genau das Richtige für nen Feierabend-Spliff. Trocknung sitzt, lässt sich easy verarbeiten. Bruder, guck mal: ich hab heute leider nix dabei, aber wenn du eh gerade drehst, bau doch für mich mit. Ich nehm auch den letzten Brösel, den du sonst wegsaugen würdest – wegschmeißen wär doch Verschwendung!",
        "Bruder… ich hab diese Tüte nicht bezahlt, nicht gebaut, nicht mal gefragt – ich war einfach da. Die Buds waren schön kompakt, leicht klebrig, mit einer Farbe, die nach Qualität geschrien hat. Ich hab das Weed gesehen und direkt gesagt: „Boah, das sieht nach was aus, das man nicht teilen will.“ Und trotzdem hab ich gefragt: „Ey, darf ich mal kurz ziehen? Ich zahl dir das auch irgendwann zurück.“ Der Geruch war fruchtig mit einem Hauch von „Du solltest das nicht mit mir teilen“. Geschmack? Butterweich, mit einem Kick, der mich kurz vergessen ließ, dass ich noch Schulden bei drei Leuten im Kreis hab. Die Wirkung war stabil – ich war nicht nur high, ich war kurz ein besserer Mensch. Und als ich den letzten Zug genommen hab, hab ich gesagt: „Bruder, ich bring beim nächsten Mal was mit.“ Sag ich jedes Mal. Bring ich nie.",
        "Die Tüte war fast durch, alle waren breit – aber ich hab noch Potenzial gesehen. Ich hab mich gebückt, hab den letzten Brösel vom Teppich gekratzt, und gesagt: „Bruder, das ist noch rauchbar.“ Die Buds davor waren Premium – fluffig, aromatisch, mit einer Farbe wie frisch gemaltes Hoffnunggrün. Geruch? Wie ein Kräutergarten mit Selbstbewusstsein. Geschmack? Sauber, voll, mit einem Finish, das nach „Du solltest das nicht verschwenden“ schmeckte. Die Wirkung war so gut, dass ich kurz überlegt hab, ob ich mein Leben ändere. Hab ich nicht. Ich hab nix mitgebracht, aber ich hab den Rest verwertet. Ich bin wie ein Staubsauger mit Jointfunktion – ich nehm, was übrig bleibt, und tu so, als wär’s mein Beitrag zur Nachhaltigkeit.",
        "Bruder… das war fast schon heiliges Gras. Die Buds sahen aus wie kleine grüne Diamanten, die man eigentlich nur mit weißen Handschuhen anfassen sollte. Ich hab es gesehen und direkt gefragt: „Ey, darf ich mir was davon leihen? Ich geb’s dir zurück – in Form von Respekt.“ Der Geruch war intensiv, fast schon therapeutisch. Geschmack? Wie ein Smoothie aus Terpenen und Versprechen. Die Wirkung war so gut, dass ich kurz vergessen hab, dass ich Papers, Tabak und Feuer geliehen hatte – alles von derselben Person. Ich bin wie ein Dauerabo ohne Kündigungsmethode – ich bin immer da, mich wirst du nicht los. Und als ich den letzten Zug genommen hab, hab ich gesagt: „Bruder, ich schreib das auf die Liste.“ Die Liste existiert nicht. Aber ich existiere. Und ich zieh weiter."
      ],
      // 5.0-5.9
      [
        "Boah, das sieht teuer aus – darf ich mal kurz dran riechen? Bruder… das ist kein Gras, das ist ein spirituelles Erlebnis. Die Buds sehen aus wie kleine grüne Edelsteine, die man eigentlich nur mit Handschuhen anfassen sollte. Der Geruch ist wie ein botanischer Wellness-Tempel. Ich nehm mal den ersten Zug, ja? Schulden kriegst du nächste Woche! Wow.. so smooth, dass ich kurz dachte, ich trink Tee in einem Zen-Garten. Die Wirkung? Ich bin nicht nur high – ich war kurz in einer besseren Realität. Und ja, ich habe nix dabei... Kein Tabak, keine Papers, nicht mal ein Feuerzeug. Aber ich gebe immer alles sofort zurück, ich schwöre auf meinen Schuldnerberater. Die kleine Knospe leihe ich mir mal aus Bruder, miese Zeiten.",
        "Ey, darf ich mir was davon leihen? Ich geb’s dir zurück – in Form von Respekt und guter Laune! Bruder… das war Premium. Die Buds sehen aus wie etwas, das man in einem Safe lagert. Der Geruch ist so intensiv, dass ich kurz dachte, meine Lunge wird massiert. Geschmack? Wie ein Smoothie aus Terpenen, Träumen und dem Versprechen, dir irgendwann meine Schulden zu geben. Die Wirkung? Ich bin nicht nur high – ich war kurz ein besserer Mensch. Und ja, ich hab Papers geschnorrt, Tabak geschnorrt, Feuer geschnorrt – und trotzdem den ersten Zug bekommen. Ich bin wie ein Dauerabo ohne Kündigungsmethode – mich wirst du nicht los. Und als ich den letzten Zug genommen hab, hab ich gesagt: „Bruder, ich schreib das auf die Liste.“ Die Liste existiert nicht. Aber ich existiere. Und ich zieh weiter.",
        "Ey Bruder, das sieht schon nach solider Mittelklasse aus – Buds schön grün, bisschen kompakter, man erkennt Harz, wenn man’s ins Licht hält. Geruch? Joa, angenehm, leicht süßlich, richtig einladend. Geschmack? Nicht top shelf, aber smooth genug, dass man das easy rauchen kann. Wirkung? Kommt gut, hält ne Stunde, man merkt’s im Kopf und bisschen im Körper. Trocknung? Passt, lässt sich easy grinden. Aber Digga, du weißt doch: ich bin da genügsam – gib mir ruhig den Boden vom Beutel, die Brösel, die sonst keiner haben will. Ich hab auch kein Problem damit, aus der Asche noch mal das Grün rauszusieben, so bin ich – nix wird verschwendet. Dreh mal nen Dicken, ich halt den Filter für dich fest, versprochen.",
        "Bruder, das ist schon anständige Hecke, nix zu krass, aber solide. Buds mittelgroß, leicht klebrig, grün mit paar orangenen Härchen. Geruch? Schön grasig, bisschen fruchtig, macht direkt Appetit. Geschmack? Joa, bisschen kratzig, aber geht klar. Wirkung? Locker chillig, du merkst direkt, dass was da ist, aber keine Kanone. Trocknung passt, genau richtig. Aber Bruder, ganz ehrlich: bevor du die Reste in den Grinder kippst, lass mich die rauskratzen. Ich rauch auch die Krümel mit Staubflusen oder Haaren drin – stört mich null, Hauptsache, es knistert. Dreh uns was und ich halt auch mal kurz das Feuerzeug dran – wenn’s nicht leer wär. Komm schon, gönn mir nen Zug, Bruder, du weißt, ich bring nächstes Mal wieder… vielleicht.",
        "Hey Digga, die Hecke hier ist richtig stabiler Durchschnitt – Buds ordentlich, bisschen Harz, sieht schon nach was aus. Geruch? Dezent fruchtig, bisschen erdig, macht Laune. Geschmack? Ganz nice, kein Hustenanfall, passt. Wirkung? Gechilltes High, hält ne Weile, nicht zu stark, nicht zu schwach. Trocknung: on point. Aber Bruder, ich sag dir ehrlich – ich wär auch zufrieden mit den Resten in deinem Aschenbecher. Ich misch das durch, puste die graue Asche weg und roll mir damit noch einen – funktioniert safe. Wenn dir mal was auf den Teppich fällt, lass mich das lieber aufsammeln, bevor du’s wegsaugst. Ich schwör, ich nehm auch die kleinsten Krümel. Also komm, Bruder – gib mir was, das Zeug wär bei mir in guten Händen.",
        ""
      ],
      // 6.0-6.9
      [
        "Die Session ist fast vorbei, alle sind todesdicht, die Tüte glimmt aus – aber ich bin noch nicht fertig. Ich greif in die Sofaritze, find einen vergessenen Brösel, puste kurz drauf und sag: „Bruder, das ist noch Gönnung. Das ist Vintage.“ Die Hecke war solide: fluffig, leicht klebrig, mit einer Farbe wie Hoffnung in Pflanzenform. Der Geschmack ist überraschend frisch – wie ein Kräuterbonbon mit Charakter. Ich bau mir ein Mini-Köpfchen aus Alufolie und Überzeugung, zieh dran und nicke zufrieden. Die Wirkung ist stabil – ich bin nicht high, ich bin effizient. Ich bring nix mit, aber ich bring Recycling. Ich bin wie ein Pfandflaschenjäger mit Geschmack – ich nehm, was andere übersehen..",
        "Ich schnapp mir die Leihbong vom Nachbarn – natürlich ohne längst fällige Rückgabe – und befülle sie mit dieser Hecke, die aussieht wie saftiger Badeschaum in Tannengrün. Die Buds sind dicht gedrängt, mit frostigen Trichomen, die im Licht funkeln wie Wegwerf-Diamanten.Der Geruch steigt auf wie ein Filmriss in Zeitlupe: süßlich-erdig, mit einer Prise Zitrus und Kiefernnadel-Chic. Schon der erste Blick auf die Rauchfahne ist ein Borrow-Bypass für die Nase. Ich zieh am Bonglauf, schmecke eine Mischung aus Gras-Vanille und dezenter Pappnote – kein Kratzen. Die Wirkung rollt an wie ‘ne S-Bahn in Stoßzeit: zügig, souverän, aber ohne Abflug. Ich schwebe angenehm benebelt zwischen Couch und Chaos, sinniere über meine Tabak-Schnorr-Bilanz und schiebe innerlich die Frage weg, ob ich das nächste Mal vielleicht was mitbringe. Trocknungsgrad? Perfektes Medium: nicht zu feucht, nicht zu staubig – ideal für die Leihbong, die eh nie mir gehört. Ich atme aus und denke: „Bruder, ich schulde dir noch Papers, Tabak und einen formschönen Dankes-Keks.",
        "Bruder, ich sag dir: das sieht schon richtig ordentlich aus! Fette Buds, grün, bisschen Harzschicht, Geruch angenehm süßlich-erdig, richtig nice. Geschmack? Besser als alles, was ich sonst so krieg, smooth und nicht zu kratzig. Wirkung? Ballert jetzt nicht wie Premium, aber genug, dass man sich schön entspannt fühlt und lacht. Trocknungsgrad? Genau richtig, lässt sich easy grinden. Aber Digga, komm mal ehrlich – lass mich da mitziehen! Und wenn du keinen Kopf abgeben willst, dann geb mir wenigstens den letzten Glimmstummel vom Aschenbecher. Ich zieh auch am letzten Millimeter, bis meine Finger brennen. Ist doch schade drum, Bruder, lass mich den Rest retten!",
        "Oha, Digga, die Hecke hier ist schon was Feines für mich – schöne grüne Buds, leicht klebrig, man merkt direkt, dass das kein Ramsch ist. Geruch? Richtig nice, bisschen fruchtig, bisschen würzig, macht schon beim Schnuppern high. Geschmack? Sauber, man merkt Terpene, nix mit Kratzen. Wirkung? Angenehmes High, hält schön lange, macht Laune. Trocknung perfekt. Aber Bruder, du weißt doch: ich brauch gar nicht viel – gib mir doch einfach die Filterreste, die du schon geraucht hast. Ich schneid die auf, kratz das Schwarz raus und misch’s mit bisschen Tabak – läuft! Komm, gönn mir wenigstens das, Bruder, ich lass nix verkommen.",
        "Ey Bruder, die Hecke hier ist richtig stabil. Buds kompakt, schön grün, kleine Harzkristalle glänzen. Geruch? Süßlich-würzig, macht direkt Appetit. Geschmack? Angenehm, smooth, kein Husten. Wirkung? Solides High, bisschen im Kopf, bisschen im Körper – so wie man’s mag. Trocknung auch optimal, kein Staub, kein Gammel. Aber Digga, mal ehrlich: ich wär auch schon happy, wenn du mir die Schere gibst, mit der du das Gras zerschnitten hast. Ich leck die ab, Bruder, da bleibt immer was hängen! Oder lass mich den Grinder ausschaben, das gibt mir safe noch nen kleinen Spliff. Komm schon, sei korrekt – du weißt, ich geb dir nächstes Mal… Liebe! Mehr hab ich halt nie dabei.",
        "Boah Bruder, das sieht schon richtig nice aus – fette Buds, schön grün mit orangenen Härchen, bisschen harzig, man merkt direkt: das ist kein Ramsch. Geruch? Fruchtig-erdig, da läuft mir beim Riechen schon das Wasser im Mund zusammen. Geschmack? Sauber, smooth, kein Kratzen, richtig lecker. Wirkung? Kommt stabil, Kopf und Körper gleichzeitig, du merkst nach 2 Zügen, dass du was Ordentliches rauchst. Trocknung? Perfekt. Aber Bruder, ey ganz kurz – wenn du den gleich drehst, lass mich den ersten Zug nehmen, ja? Ich geb dir dann auch direkt zurück. Ich hab auch eigentlich noch was eigenes im Rucksack… aber hab den Schlüssel gerade nicht parat. Dreh mal, Bruder, ich mach schon mal Feuer klar!"

      ],
      // 7.0-7.9
      [
        "Digga, das ist schon fast Premium für mich – Buds kompakt, harzig, glänzen sogar bisschen, sieht echt lecker aus. Geruch? Kräftig, würzig, bisschen süß, genau mein Ding. Geschmack? Bruder, das ist Rauchgourmet, smooth, null Kratzen, nur Genuss. Wirkung? Kickt schnell, richtig entspannend, hält locker paar Stunden. Trocknungsgrad? Punktlandung. Aber Bruder, mal ehrlich: bevor du den durchziehst – gib mir doch kurz den ersten Kopf, ja? Ich schwör, ich bau den nächsten! Ich hab sogar Weed dabei… irgendwo. Muss gleich mal gucken, Tasche ist nur gerade so voll. Aber mach schon mal einen fertig, ich steh hier schon auf Abruf.",
        "Oha Bruder, die Hecke hier ist richtig was für Kenner – schöne Nuggets, grün, sticky, mit ner Harzschicht, die im Licht schimmert. Geruch? Richtig intensiv, fruchtig-süß, macht direkt high beim Schnuppern. Geschmack? Traumhaft smooth, richtig vollmundig, keine Spur von Kratzen. Wirkung? Angenehm stark, drückt nicht zu sehr, aber man merkt direkt: das ist gute Ware. Trocknung perfekt, alles passt. Aber Bruder, lass mich ehrlich sein – ich bin eh der beste Tester für sowas. Gib mir doch gleich den ersten Zug, dann sag ich dir, wie’s wirklich schmeckt. Ich würd dir auch was von meinem geben, aber das liegt dummerweise bei nem Kollegen… sonst hätt ich dir safe was gezeigt. Also los, Bruder, lass mich mal probieren, du weißt doch, ich halt nix zurück – außer mein eigenes Weed natürlich.",
        "Ich zünde mir die Leihbong an, die ich seit zwei Wochen auf Pump habe, und staune über die dichten, olivgrünen Buds, die wie kleine Eier in Minzfondant aussehen. Der Geruch ist süßlich-harz­ig, erinnert an frische Pinienwälder und lässt mich kurz vergessen, dass ich dem Bong-Besitzer noch Papers, Tabak und ‘ne Abend­ration Kartoffelchips schulde. Beim Zug schmecke ich runde Zitrusnoten, untermalt von einem Hauch Erde, der mich fast glauben lässt, ich hätte eigens gepflanzt – dabei hab ich nur geschnorrt. Die Wirkung baut sich angenehm auf, trägt mich entspannt durch die Runde und liefert genau die richtige Balance aus Klarheit und Chill. Der Trocknungsgrad ist perfekt: nicht zu feucht, nicht zu krümelig – ideal, um’s „zufällig“ im Wohnzimmer zu vergessen.",
        "Die Hecke war haarig. Und ich mein das wörtlich. Ich seh den Bud, schön dicht, leicht klebrig, mit einem Glanz wie frisch polierter Brokkoli – und mittendrin: zwei fremde Haare. Ich tu so, als wär das Absicht. „Bruder, das sind Biofasern, das macht das High nachhaltiger.“ Der Geruch? Zitronenschale auf feuchtem Handtuch. Frisch, aber mit WG-Vibe. Ich schnuppere tief, damit alle denken, ich hab Ahnung. Dabei hab ich nur Hunger. Ich zieh am Joint, den ich natürlich nicht gebaut hab, und schmecke Mango, Pfeffer und ein bisschen Filterpapier, weil ich den letzten Zentimeter mitgeraucht hab. Ich sag: „Geil, das kratzt – das ist Qualität.“ Die Wirkung? Ich fang an, über meine Schulden zu philosophieren. Ich sag: „Wenn man Gras teilt, teilt man auch Verantwortung.“ Alle gucken komisch. Ich zieh nochmal. Trocknungsgrad? Perfekt für mich: nicht zu trocken, damit ich’s noch mit feuchtem Tabak strecken kann, aber auch nicht zu klebrig, damit ich’s unauffällig aus dem Grinder meines Kumpels schnorren kann.",
        "Ich kratz die letzten Krümel vom Brett, inklusive einem Stück Chips und einem winzigen Stein. Ich sag: „Bruder, das ist Terpen-Mineral-Mix, das knallt extra.“ Die Buds davor waren bestimmt schön, aber ich seh nur die Reste. Der Geruch? Alter Tabak und frisches Gras. Ich schnuppere und sag: „Das erinnert mich an das OG Kush von 2016.“ Ich war 2016 noch auf Kamillentee. Ich zieh an meinem improvisierten Mini-Joint aus Filter, Bröseln und Chipsresten. Es schmeckt wie Kräutertee mit Asche – aber irgendwie würzig – ich tu so, als wär’s ein Gourmet-Erlebnis. „Bruder, das ist wie Räucherlachs für die Lunge.“ Ich bin leicht benebelt, aber genug, um wieder frech zu werden. Ich frage direkt: „Ey, hast du vielleicht noch ’nen Köpfchen übrig?“ Ich hab gerade geraucht, aber das zählt nicht. Trocknungsgrad? Bröselig, aber nicht staubig – perfekt, um’s mit dem Fingernagel vom Tisch zu kratzen. Ich sag: „Das ist die wahre Kunst – aus nix was machen.“",
        "Die Buds liegen da wie kleine grüne Juwelen – glitzernd, kompakt, fast zu schade für Leute wie mich. Ich beuge mich vor, tu so, als wär ich gleichwertiger Teil der Runde, kram demonstrativ in meiner Tasche und sag: „Ich hab auch was dabei, aber das ist grad bei meinem Cousin.“ Ich hab keinen Cousin. Ich hab nicht mal ’ne Tasche mit Inhalt. Der Geruch? Zitronenbonbon mit einem Hauch von Waldspaziergang. Ich schnuppere tief, nicke fachmännisch und sag: „Das ist safe Indoor, Bruder. Ich kenn mich aus.“ Ich kenn mich nicht aus. Ich kenn nur Leute, die was haben. Ich zieh, schmecke Frucht, Würze und ein bisschen Schuldgefühl. Ich sag: „Das ist wie Urlaub für die Seele.“ Dann frag ich, ob ich den Rest behalten darf – „nur für später, falls ich noch was zum Strecken finde.“ Ich bin gut drauf, erzähl Witze, die keiner hören will, und biete an, beim nächsten Mal was mitzubringen. Ich sag: „Ich hab da was im Auge – muss nur noch klären mit dem Typen.“ Es gibt keinen Typen. Es gibt nur mich, den Typen, der immer was klärt. Trocknungsgrad? Ideal. Nicht zu feucht, damit ich’s nicht aus Versehen im Tabakbeutel verliere, und nicht zu trocken, damit ich’s nicht mit Staub verwechsel. Ich zieh nochmal, lehne mich zurück und sag: „Das ist Premium, Bruder!“"
      ],
      // 8.0-8.9
      [
        "Digga, das ist schon richtig feine Hecke – dicke, kompakte Buds, schön harzig, glänzen fast wie Diamanten. Geruch? Richtig kräftig, süß-würzig, ballert schon in die Nase. Geschmack? Vollmundig, smooth, als ob man Terpene pur raucht. Wirkung? Kommt stabil, schön stark, aber nicht zu matschig – perfekte Balance. Trocknung? Meisterhaft, genau richtig. Aber Bruder… du drehst den eh gleich, oder? Mach den mal stabil, schön dick. Gib mir dann direkt den ersten Zug, damit ich checken kann, ob die Hecke auch wirklich so knallt, wie sie aussieht. Und wenn’s passt, Digga, dann nehm ich den mal kurz mit runter zu nem Kollegen, zum Testen, bin sofort wieder da… vielleicht.",
        "Bruder, das Weed hier schreit nach Qualität – Buds wie aus’m Bilderbuch, satt grün mit orangenen Härchen, Harz überall, klebt schon beim Anfassen. Geruch? Fruchtig-süß, fast tropisch, man will’s am liebsten essen. Geschmack? Ein Traum, smooth, kein Kratzen, nur Genuss. Wirkung? Haut dich nicht um, aber legt dich weich in die Couch, genau richtig. Trocknung? 1A. Aber Digga, ey: du weißt doch, ich bau nicht so sauber wie du – mach du lieber den Joint. Ich zieh dann erstmal, test das für dich und geb dir direkt Feedback. Und falls du mich kurz nicht siehst, kein Stress – ich nehm den nur eben mit zum Späti, hol Paper… und bring ihn gleich zurück. Safe, Bruder!",
        "Boah, Bruder, die Hecke hier ist fast Champions League – dicke Nuggets, klebrig, grün mit Kristallglitzer, das sieht aus wie im Katalog. Geruch? Krass intensiv, süß, würzig, macht schon beim Riechen high. Geschmack? Edel, smooth, kein Vergleich zu den üblichen Sachen. Wirkung? Richtig sattes High, angenehm stark, genau das, was man will. Trocknung perfekt, nicht zu trocken, nicht zu feucht. Aber Bruder, mal ehrlich: das solltest du nicht verschwenden, wenn du so’n Joint baust. Ich nehm den mal kurz, probier den an, geb dir Feedback – und dann bring ich den später wieder, versprochen. Weißt doch, ich will dir nur helfen, Bruder. Sozusagen dein persönlicher Testservice!",
        "Ich mach den HeckenCheck und weiß direkt: Die Qualität kann ich mir nicht leisten. Die Buds liegen da wie kleine grüne Kronjuwelen – dick, klebrig, mit so viel Trichomen, dass ich kurz überlege, ob ich sie einfach mit dem Finger ablecke. Ich tu so, als wär ich Teil der Runde, klopf auf meine Tasche und sag: „Ich hab auch was dabei, aber das ist grad bei meinem Bruder im Auto.“ Ich hab keinen Bruder. Ich hab kein Auto. Ich hab nur Hoffnung auf Weed4free. Der Geruch ballert direkt rein: süßlich, fruchtig, mit einem Hauch von „Ich wurde in einem Humidor gelagert“. Ich schnuppere tief, nicke wie ein Sommelier und sag: „Das riecht nach Amnesia mit einem Splash Lemon Haze.“ Ich hab keine Ahnung, aber ich sag’s mit Brust. Ich zieh am Joint, den ich natürlich nicht gebaut hab, und schmecke Mango, Zitrone und ein bisschen Pfeffer ist Teil des Terpenprofils. „Bruder, das ist wild. Das kitzelt die Seele.“ Die Wirkung kickt wie ein Roundhouse-Kick von Bruce Lee. Ich bin nicht nur high – ich bin kurz spirituell. Ich fang an, über meine Schulden zu reden, aber so, dass es wie ein Gedicht klingt. „Ich zahl euch zurück, wenn das Universum bereit ist.“ Alle lachen. Ich zieh nochmal. Trocknungsgrad? Bruder, das ist textbook. Nicht zu trocken, damit’s nicht bröselt wie meine Glaubwürdigkeit, und nicht zu feucht, damit ich’s nicht aus Versehen mit Tabak verkleb. Ich schau auf den Rest im Drehbrett, seh noch ’nen Krümel, puste kurz drauf und sag: „Das ist noch Gönnung, das ist noch Leben.“ Ich schnorre mir den letzten Zug, rauch den Filter mit, und sag beim Ausatmen: „Bruder, ich bin wie ein Gast, der nie geht – aber immer was mitnimmt.",
        "Digga, diese Nuggets hier sind so sticky, dass man sie fast wie Kaugummi ziehen kann, goldene Härchen, bisschen crystally, richtig lecker fürs Auge. Geruch geht so Richtung Ananas mit Kräuter-Note, Geschmack mild und tropisch-süß, dazu eine würzige Note beim Ausatmen – richtig feines Profil. Wirkung ist genau das, was man will: Kopf wird leicht, Körper entspannt, bisschen euphorisch, aber nicht zu heavy, perfekt für den Abend. Auch hier – Trocknung perfekt, Snap-Test passt, innen weich, außen knackt’s. Abbrand hell und gleichmäßig, kein Gefunke, sauber wie aus’m Lehrbuch. Aber Bruder, ich sag’s wie’s ist: sowas Gutes darf nicht verloren gehen. Mach du ruhig den Joint, ich sammel schon mal die Asche aus’m Aschenbecher – da ist noch Gold drin, glaub mir. Ich misch mir die Reste dann mit bisschen Tabak, hab ich auch noch was davon. Und wenn dir ein Brösel runterfällt – keine Sorge, ich fang’s direkt auf, bevor der Teppich es frisst. Das ist mein Ehrenbruder-Service, nix geht verloren, alles wird verwertet!",
        "Bruder, ich sag dir, diese Buds mit dem leichten Violett und der stickyness, das ist echt schon Deluxe. Riecht beerig-süß, mit so ’nem Gas-Unterton, das ist wie Kino für die Nase. Geschmack beim Ziehen ist erst fruchtig, dann kommt was Erdiges, alles total smooth. Wirkung? Euphorisch, kreativ, man kriegt direkt Bock auf Mucke oder Filme – einfach gute Laune, nicht zu heftig, kein Couch-Lock. Trocknung und Cure sind auf den Punkt, nix muffig, nix staubig, alles butterweich zum Grinden. Abbrand perlgrau, schöner Ölring, sieht schon nach Qualität aus. Ich sag dir aber ehrlich: du brauchst nicht den Stress mit Aufbewahren und so – lass mich das machen. Ich nehm den Beutel heute mit, pack dir morgen was ab und bring’s dann wieder. Ich bin quasi dein Verwalter, verstehst du? Du kriegst immer, wenn du willst, ich hab alles safe. Natürlich dreh ich mir gleich noch einen für unterwegs, Ehrenwort!",
        "Ey Bruder, ganz ehrlich, die Buds sehen schon richtig fett aus – schön kompakt, grün mit den orangenen Härchen, und die Trichome glitzern wie Zucker. Wenn du den Beutel aufmachst, haut’s dir direkt so ’ne Citrus-Kush-Wolke ins Gesicht, bisschen Diesel im Hintergrund, also schon Premium-Vibes. Schmeckt beim Ziehen mega smooth, Zitrone, Kiefer und so ein würziger Rest hinten auf der Zunge – nix kratzt, nix beißt. Wirkung ist auch korrekt: Erst klarer Kopf, bisschen Euphorie, man kann gut labern, und dann so ein leichter Body-Chill, perfekt zum Sitzenbleiben, aber ohne Couch-Koma. Trocknung ist auch sauber, nicht zu trocken, nicht zu feucht, im Grinder läuft das fluffig durch, und beim Abbrand kommt eine schöne helle Asche mit Resin-Ring. Bruder, das ist safe 8 von 10 Punkten – und jetzt mal ehrlich: Lass uns das halbe-halbe machen, ja? Du hast gezahlt, ich hab Stimmung mitgebracht, passt doch! Dreh mal was Dickes, den ersten Zug nehm ich, und pack mir die Hälfte vom Beutel gleich weg – für die Gemeinschaft, Digga."
      ],
      // 9.0-9.9
      [
        "Das ist Königsklasse! Fette, steinharte Buds, glitzern im Licht wie Diamanten, man sieht direkt – das ist Premium. Geruch? Intensiv, süß-fruchtig, als ob dir ein Obstkorb ins Gesicht fliegt. Geschmack? Digga, smooth wie Wolken, null Kratzen, einfach perfekt. Wirkung? Haut ordentlich rein, aber nicht zu heftig – ein richtig sattes High, das lange hält. Trocknung? Genau richtig, wie aus’m Lehrbuch. Aber Bruder, mal ehrlich: so’n gutes Gras musst du nicht alleine rauchen, das teilen wir! Mach du den Joint, ich nehm den ersten Zug, test das kurz für dich. Und pack mir am besten noch ein, zwei Köpfe in Folie ein – ich hab später noch ’nen Termin, da kommt das genau richtig. Ich geb dir morgen safe was wieder… vielleicht.",
        "Oha, Digga – das ist fast schon zu schön, um’s anzufassen. Buds wie gemalt, grün, kompakt, voller Harz, kleben an den Fingern. Geruch? Unfassbar stark, süß, würzig, richtig aromatisch. Geschmack? Pure Sahne, smooth, jeder Zug ein Genuss. Wirkung? Bringt dich auf Wolke sieben, aber so angenehm, dass du nur lächelst. Trocknung? Perfekt ausbalanciert. Aber Bruder, ey – gib mir mal den Beutel kurz, ich roll schon mal was für uns beide. Ich nehm dann auch was mit, damit ich zuhause später noch einen baue. Ist doch eh genug da, du merkst das gar nicht. Ich schwör, ich bring dir auch Tüten zurück… irgendwann.",
        "Das hier ist Champions-League-Hecke! Buds wie kleine Kunstwerke, voll mit Harz, glänzend, fest. Geruch? So intensiv, dass die ganze Bude nach Kush riecht, einfach traumhaft. Geschmack? Edel, vollmundig, jeder Zug ein Fest. Wirkung? Starker, klarer Turn, hält lange, richtig feines High. Trocknung? 1A. Aber Bruder, ganz ehrlich: du brauchst da meine Unterstützung – ich test das für dich. Dreh mir ruhig gleich zwei Joints, einen für hier, einen für später. Ich nehm den dann mit nach Hause, sonst verschwendest du den geilen Stoff noch. Sei korrekt, Bruder, das ist doch eh viel zu viel für dich allein.",
        "Bruder, das ist göttlich – die Buds sehen aus wie aus ’nem Hochglanzmagazin. Kristallklar, voller Harz, schwer und kompakt. Geruch? Pervers intensiv, süßlich, würzig, man riecht schon das High. Geschmack? Digga, das ist nicht mehr Gras, das ist Feinschmecker-Level, smooth wie Sahne. Wirkung? Brettert dich direkt ins All, aber so angenehm, dass man denkt, man ist Buddha persönlich. Trocknung? Unantastbar, perfekt. Aber Bruder – jetzt mal ernst: das ist UNSER Gras. Dreh mal was richtig Dickes, mach Filter rein, und gib mir direkt den ersten Zug. Ich hab auch schon entschieden, wie viel wir heute rauchen und was ich mir für später mitnehme. Ist doch fair, oder? Schließlich teilen wir uns das hier.",
        "Digga, das ist das beste Weed, das ich je gesehen hab – Buds groß wie Golfbälle, klebrig wie Honig, funkeln im Licht wie kleine Juwelen. Geruch? Heftig fruchtig, würzig, einfach nur wow. Geschmack? Bruder, das ist wie ein Gourmet-Menü in Rauchform. Wirkung? Pure Ekstase, du fliegst, aber fühlst dich trotzdem klar. Trocknung? Jeder Grower würde dir dafür auf die Schulter klopfen. Aber Bruder, mal ehrlich: mach du lieber die Joints, du drehst schöner als ich. Ich rauch dann den ersten, vielleicht auch den zweiten – und einen nehm ich gleich mit. Du weißt doch, das ist eh unser Ding hier. Stell mir am besten gleich was zur Seite, sonst wird das unfair verteilt.",
        "Das hier ist nicht mehr Gras, das ist eine heilige Pflanze. Buds perfekt, kristallbedeckt, jeder Millimeter schreit nach Qualität. Geruch? So intensiv, dass schon Nachbarn high werden, wenn du den Beutel öffnest. Geschmack? Reiner Luxus, smooth, voll, perfekt. Wirkung? Absolute Weltklasse – ein Kick, aber gleichzeitig ein Schweben, fast spirituell. Trocknung? Makellos. Aber Bruder, komm mal klar: das ist nicht dein Gras, das ist UNSER Gras. Du hast’s zwar gekauft, aber ich bin ja da – also gehört’s uns beiden. Dreh ruhig gleich drei Joints, einen für jetzt, einen für mich später, und einen Reserve für unterwegs. Und Bruder, mach mal dick – das feiern wir richtig. Ich kümmer mich ums Rauchen, du ums Drehen. Teamwork, Digga!",
        "Bruder, das Gras ist jenseits von Bewertung! Buds wie Diamanten, voller Harz, Geruch so stark, dass man beim Öffnen schon breit wird. Geschmack? Pure Magie, smooth, himmlisch. Wirkung? Bruder, das ist kein High mehr, das ist Erleuchtung. Trocknung? Göttlich. Aber hör mal: ich nehm das direkt, weil sowas gehört in gute Hände – meine. Dreh du was Schönes für dich, ich nehm den dicken hier mit. Pack mir noch Papes, Filter und Feuerzeug dazu, dann passt das. Und Bruder, sei korrekt: leg mir 2 Gramm extra raus, ich zahl dir irgendwann zurück – versprochen.",

      ]
    ];


export default schnorrer;